### ISSUE TITLE
Plugin broken on latest version of MO2

### ISSUE THREAD

**Issue by ImTrep** [Exit-9B/LOOTConfigLoader#1]
Skyrim 1.6.640 SKSE 2.2.3
MO2 Version: 2.5.0

Here's the error:
![image](https://github.com/Exit-9B/LOOTConfigLoader/assets/131490609/bd5a9d2c-53f5-460f-9abe-2b6b99411410)

**Comment by loicreynier** [comment]
You can fix it by replacing `PyQt5` by `PyQt6` in `lootconfigloader/lootconfigmapper.py` as in #2.

**Comment by ImTrep** [comment]
it's working now, thanks!
